version: '3'

services:
  web:
    restart: always
    build: .
    volumes:
      - ./static:/dist
      - ./log:/log
    env_file: .env
    command: ["/code/config/wait-for-it.sh", "db:3306", "--", "bash","config/boot.sh"]
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./static:/usr/share/nginx/html/static
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - web
    depends_on:
      - web
  db:
    restart: always
    image: mariadb:latest
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - ./data/initsql:/docker-entrypoint-initdb.d
      - ./data/db:/var/lib/mysql
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
