"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# SECURITY WARNING: don't run with debug turned on in production!


DEBUG = False if os.environ.get("DEBUG") == 'false' else True


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'x8et$7a+4lwhko-0a%%%kqp4rb&@3&ee_616(3(q9&%+3n@9pl'

ALLOWED_HOSTS = []

LOGIN_URL = '/login'
LOGIN_REDIRECT_URL = '/'

# Application definition
INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app.Index',
    'mdeditor',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    }
]

# 设置静态文件URL
STATIC_URL = '/static/'

# 设置静态文件夹目录的路径
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'app', 'Index', 'static'),
)

# 设置文件上传路径，图片上传、文件上传都会存放在此目录里
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')

LANGUAGE_CODE = 'zh-hans'

USE_TZ = False
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Use some debug tools in development.
if DEBUG:
    INSTALLED_APPS.append('debug_toolbar')
    STATIC_ROOT = os.path.join(BASE_DIR, 'dist')
    TIME_ZONE = 'Asia/ShangHai'

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }

    MIDDLEWARE.append('debug_toolbar.middleware.DebugToolbarMiddleware')

    # for debug-toolbar
    INTERNAL_IPS = [
        '127.0.0.1'
    ]


# In production, we will rewrite some settings.
else:
    # logging
    import logging
    LOG_FORMAT = "%(asctime)s - %(levelname)s - %(message)s"
    logging.basicConfig(filename='/log/django.log',
                        level=logging.DEBUG, format=LOG_FORMAT)

    # safety
    SECRET_KEY = os.environ.get('SECRET_KEY')
    ALLOWED_HOSTS = [
        '*'
    ]
    # Not HTTPS... temporarliy
    SECURE_SSL_REDIRECT = False

    # Use more strict password strategy
    AUTH_PASSWORD_VALIDATORS.extend([
        {
            'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
        }
    ])

    # Use MySQL
    DBPSWD = os.environ.get('MYSQL_PASSWORD')
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'django',
            'USER': 'root',
            'PASSWORD': DBPSWD,
            'HOST': 'db',
            'PORT': '3306',
            'OPTIONS': {'charset': 'utf8mb4'}
        }
    }

    # Static files is in /dist. See docker-compose.yml
    STATIC_ROOT = os.path.join('/dist')
SESSION_EXPIRE_AT_BROWSER_CLOSE = True